Try to avoid recursive repr() calls*
For details refer to the following failing build:
https://travis-ci.org/xolox/python-apt-mirror-updater/jobs/395417400

This recurses until it hits the following exception:

  RecursionError: maximum recursion depth exceeded
                  while calling a Python object

Clearly not intended behavior! I hope that this change is enough
to resolve the problem, but I guess I'll find out as soon as I
push this change to Travis CI :-).